I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 7, in script
    SilverSexyWoman "You've created a new Ren'Py game."
Exception: Sayer 'SilverSexyWoman' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 7, in script
    SilverSexyWoman "You've created a new Ren'Py game."
  File "C:\Users\Admin\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Admin\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 581, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\Admin\Downloads\renpy-8.3.4-sdk\renpy\ast.py", line 470, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'SilverSexyWoman' is not defined.

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
FafNovel 1.0
Thu Feb 27 13:10:55 2025
